### ISSUE TITLE
Question about decomposition field

### ISSUE THREAD

**Issue by LEEJUHUI6635** [lsongx/nerfplayer-nerfstudio#2]
Hello. Firstly, thank you for your nice work. It might be helpful for understanding the paper. 

While studying your code, I couldn't find the deformation field network, decomposition field and summation of probability and the feature vector which are proposed in the paper. Then, I wonder if you implemented these parts not yet. 

Thank you for your nice work, again.

**Comment by lsongx** [comment]
@LEEJUHUI6635 Not implemented on nerfstudio. Please send me an email and I’ll share you another version of code.
