### ISSUE TITLE
why my command Line is stay at " nerfstudio field components: CUDA set up, loading (should be quick)"

### ISSUE THREAD

**Issue by xiazhi1** [lsongx/nerfplayer-nerfstudio#5]
I train the nerfplayer with example: ns-train nerfplayer-ngp --data dycheck/teddy/, and it keeps stay this status for a long time nearly an hour, is it normal?
My environment is like below:
nerfplayer                0.0.1        /root/autodl-tmp/nerfplayer-nerfstudio
nerfstudio                0.3.2        /root/autodl-tmp/nerfstudio
torch                     2.0.1+cu117
torch-fidelity            0.3.0
torchaudio                2.0.2
torchmetrics              1.0.1
torchtyping               0.1.4
torchvision               0.15.2+cu117
tornado                   6.3.2
tinycudann                1.7
Ubuntu 20.04
python 3.8

Looking forward to your reply 
@lsongx

**Comment by lsongx** [comment]
Hi @xiazhi1 , do you mind posting what is happening during waiting (perhaps by `htop`)? Also, does it work after waiting for a long time? It may take a long time to compile the cuda source, depending on your hardwares, but an hour sounds indeed long.

**Comment by xiazhi1** [comment]
> Hi @xiazhi1 , do you mind posting what is happening during waiting (perhaps by `htop`)? Also, does it work after waiting for a long time? It may take a long time to compile the cuda source, depending on your hardwares, but an hour sounds indeed long.

These photos shows my cpu and gpu 's usage， it seems like the train is not use GPU to train? Why is this?
![e72f35d1a95922a46da48d70c272993](https://github.com/lsongx/nerfplayer-nerfstudio/assets/91876721/7b9f0e70-15d9-4984-8363-86089fb4fc2e)
![5fecae13244bb0a8f6a991c24b12b0c](https://github.com/lsongx/nerfplayer-nerfstudio/assets/91876721/af5fb198-ef9b-4b16-a4c8-4a469b5c8a62)

**Comment by xiazhi1** [comment]
@lsongx

**Comment by lsongx** [comment]
That's weird. Both GPU and CPU are not being used. 😕

**Comment by Friedrich-M** [comment]
I met the same problem. Both GPU and CPU are not being used.

<img width="899" alt="image" src="https://github.com/lsongx/nerfplayer-nerfstudio/assets/85838942/6eb23838-d4d8-4b6a-a90e-e3d5d48a1e53">

**Comment by Friedrich-M** [comment]
@xiazhi1 I solve the problem by removing the cache of the build directory because pytorch jit might stuck if the build directory exists.

You can use the command as followed

```bash
rm -rf ~/.cache/torch_extensions/py38_cu118/nerfstudio_field_components_cuda
```
